export const projectData = [
  {
    id: 'ai_pdf_gen',
    name: 'AI PDF Generator',
    icon: '🧾',
    description: 'Generates professional PDF documents from various data sources using AI.',
    installStatus: 'installed', // 'installed', 'not_installed', 'installing'
    isRunning: false,
    isLoading: false,
    error: null,
    scriptName: 'pdf_generator',
    logs: [
      'PDF Generator v1.0 initialized.',
      'Ready to process requests.',
      'Last run: 2023-10-27 10:30:15',
    ],
  },
  {
    id: 'resume_gen',
    name: 'Resume Generator',
    icon: '📄',
    description: 'Crafts tailored resumes and cover letters based on job descriptions and user profiles.',
    installStatus: 'not_installed',
    isRunning: false,
    isLoading: false,
    error: null,
    scriptName: 'resume_gen',
    logs: [],
  },
  {
    id: 'meme_bot',
    name: 'Meme Bot',
    icon: '🎭',
    description: 'Generates topical and humorous memes on demand for social media.',
    installStatus: 'installed',
    isRunning: false,
    isLoading: false,
    error: null,
    scriptName: 'meme_bot',
    logs: [
      'Meme Bot activated. Listening for commands.',
      'Generated "AI takes over the world" meme.',
    ],
  },
  {
    id: 'tiktok_predictor',
    name: 'TikTok Predictor',
    icon: '🔮',
    description: 'Analyzes TikTok trends and predicts viral content potential.',
    installStatus: 'installed',
    isRunning: true, // Example of a running project
    isLoading: false,
    error: null,
    scriptName: 'tiktok_predictor',
    logs: [
      'TikTok Predictor service started.',
      'Analyzing hashtag #AIArt. Predicted virality: 85%',
      'New trend detected: "Retro Futurism".',
      'Prediction complete for "Dancing Robots".',
    ],
  },
  {
    id: 'voiceover_studio',
    name: 'Voiceover Studio',
    icon: '🗣️',
    description: 'Converts text to natural-sounding speech with various voice options.',
    installStatus: 'not_installed',
    isRunning: false,
    isLoading: false,
    error: null,
    scriptName: 'voiceover_studio',
    logs: [],
  },
  {
    id: 'seo_listicle_builder',
    name: 'SEO Listicle Builder',
    icon: '🧠',
    description: 'Generates SEO-optimized listicle articles based on keywords and topics.',
    installStatus: 'installed',
    isRunning: false,
    isLoading: false,
    error: null,
    scriptName: 'seo_listicle_builder',
    logs: [
      'SEO Listicle Builder ready.',
      'Last article: "Top 10 AI Tools for Small Businesses".',
    ],
  },
  {
    id: 'ai_bio_page_gen',
    name: 'AI Bio Page Generator',
    icon: '🔗',
    description: 'Creates personalized, engaging bio pages for professionals and creatives.',
    installStatus: 'not_installed',
    isRunning: false,
    isLoading: false,
    error: null,
    scriptName: 'bio_page_gen',
    logs: [],
  },
  {
    id: 'career_glowup_bot',
    name: 'Career Glow-Up Bot',
    icon: '📬',
    description: 'Provides personalized career advice, interview prep, and networking tips.',
    installStatus: 'installed',
    isRunning: false,
    isLoading: false,
    error: 'Failed to connect to LinkedIn API.', // Example of an error
    scriptName: 'career_bot',
    logs: [
      'Career Glow-Up Bot initializing...',
      'Error: Could not authenticate with LinkedIn API. Please check credentials.',
    ],
  },
  {
    id: 'cybersec_newsletter_bot',
    name: 'Cybersecurity Newsletter Bot',
    icon: '🧑‍💻',
    description: 'Curates and summarizes daily cybersecurity news for a tailored newsletter.',
    installStatus: 'installed',
    isRunning: true,
    isLoading: false,
    error: null,
    scriptName: 'cybersec_bot',
    logs: [
      'Cybersecurity Newsletter Bot running.',
      'Fetching latest threats from Dark Web monitors.',
      'Compiling daily digest...',
    ],
  },
];
